#!/usr/bin/env bash
# supabase-tenant-rbac installer / migration generator.
#
# Generates plain SQL migration files from TLE-compatible extension SQL.
# Works both locally (inside the repo) and remotely (via curl from GitHub).
#
# Usage (remote — from your Supabase project directory):
#   curl -sL https://raw.githubusercontent.com/point-source/supabase-tenant-rbac/main/tools/install.sh | bash
#   curl -sL .../tools/install.sh | bash -s -- --from 5.0.0
#   curl -sL .../tools/install.sh | bash -s -- --schema my_rbac --version 5.1.1
#
# Usage (local — from the repo root):
#   tools/install.sh                              # Regenerate dev install migration
#   tools/install.sh --from 5.0.0                 # Upgrade migration to stdout
#   tools/install.sh --from 5.0.0 -o upgrade.sql  # Upgrade migration to file
#
# Options:
#   --schema NAME       Schema name (default: rbac)
#   --version X.Y.Z     Target version (default: from control file or VERSIONS manifest)
#   --from X.Y.Z        Generate upgrade migration instead of fresh install
#   -o, --output FILE   Output file (default: see below)
#   --output-dir PATH   Output directory for timestamped filename (remote mode only)
#   --branch NAME       GitHub branch to download from (default: main)
#   --dry-run           Print what would be done without writing files
#
# Output defaults:
#   Local install:   supabase/migrations/20240502214828_install_rbac.sql (fixed, diffed)
#   Remote install:  supabase/migrations/<timestamp>_install_rbac.sql
#   Upgrade:         stdout (use -o to write to file)

set -euo pipefail

# --- Detect local vs remote mode ---
# If we can find the repo root (control file + SQL files), use local mode.
REPO_ROOT=""
SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" ]] && [[ -f "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    candidate="$(cd "$SCRIPT_DIR/.." 2>/dev/null && pwd)"
    if [[ -f "$candidate/supabase_rbac.control" ]]; then
        REPO_ROOT="$candidate"
    fi
fi

LOCAL_MODE=false
if [[ -n "$REPO_ROOT" ]]; then
    LOCAL_MODE=true
fi

GITHUB_RAW="https://raw.githubusercontent.com/point-source/supabase-tenant-rbac"
BRANCH="main"
SCHEMA="rbac"
VERSION=""
FROM_VERSION=""
OUTPUT_FILE=""
OUTPUT_DIR=""
DRY_RUN=false

# --- Argument parsing ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --schema)     SCHEMA="$2";      shift 2 ;;
        --version)    VERSION="$2";     shift 2 ;;
        --from)       FROM_VERSION="$2"; shift 2 ;;
        -o|--output)  OUTPUT_FILE="$2"; shift 2 ;;
        --output-dir) OUTPUT_DIR="$2";  shift 2 ;;
        --branch)     BRANCH="$2";      shift 2 ;;
        --dry-run)    DRY_RUN=true;     shift ;;
        -h|--help)
            sed -n '2,/^$/{ s/^# \{0,1\}//; p; }' "${BASH_SOURCE[0]:-$0}" 2>/dev/null \
                || echo "supabase-tenant-rbac installer. Use --help for options."
            exit 0
            ;;
        *) echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
    esac
done

BASE_URL="${GITHUB_RAW}/${BRANCH}"

# --- Helpers ---
die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

# Fetch a URL via curl (remote mode only)
fetch_url() {
    local content
    if ! content=$(curl -fsSL "$1" 2>/dev/null); then
        die "Failed to download: $1"
    fi
    printf '%s\n' "$content"
}

# Get SQL file content — local file or remote URL
get_sql() {
    local filename="$1"
    if $LOCAL_MODE && [[ -f "$REPO_ROOT/$filename" ]]; then
        cat "$REPO_ROOT/$filename"
    else
        fetch_url "${BASE_URL}/${filename}"
    fi
}

# --- Validate schema name ---
if ! echo "$SCHEMA" | grep -qE '^[a-z_][a-z0-9_]*$'; then
    die "Invalid schema name: '$SCHEMA' (must match [a-z_][a-z0-9_]*)"
fi

# --- Resolve version ---
if [[ -z "$VERSION" ]]; then
    if $LOCAL_MODE; then
        VERSION=$(grep "^default_version" "$REPO_ROOT/supabase_rbac.control" \
            | sed "s/default_version = '\\(.*\\)'/\\1/")
    else
        manifest=$(fetch_url "${BASE_URL}/VERSIONS")
        VERSION=$(echo "$manifest" | grep '^latest=' | cut -d= -f2 | tr -d '[:space:]')
    fi
fi
[[ -z "$VERSION" ]] && die "Could not determine target version"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "Invalid version format: $VERSION"

# --- Load manifest for upgrade path (remote mode) ---
if [[ -n "$FROM_VERSION" ]] && ! $LOCAL_MODE && [[ -z "${manifest:-}" ]]; then
    manifest=$(fetch_url "${BASE_URL}/VERSIONS")
fi

# --- Temp file with cleanup ---
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

# --- Version function (appended to every migration) ---
append_version_function() {
    cat <<VEOF

-- Version tracking (auto-generated by tools/install.sh)
CREATE OR REPLACE FUNCTION ${SCHEMA}._version()
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS \$function\$
    SELECT '${VERSION}'::text;
\$function\$;

REVOKE EXECUTE ON FUNCTION ${SCHEMA}._version() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ${SCHEMA}._version() TO authenticated, anon, service_role, authenticator;
VEOF
}

# ═══════════════════════════════════════════════════════════════════════════════
# UPGRADE MODE
# ═══════════════════════════════════════════════════════════════════════════════
if [[ -n "$FROM_VERSION" ]]; then
    # NOTE: This upgrade path is for plain SQL installations only.
    # If you originally installed via dbdev/pg_tle, upgrade via dbdev instead.
    [[ "$FROM_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "Invalid --from version: $FROM_VERSION"

    if [[ "$FROM_VERSION" = "$VERSION" ]]; then
        info "Already at version $VERSION — nothing to upgrade."
        exit 0
    fi

    current="$FROM_VERSION"
    steps=0

    while [[ "$current" != "$VERSION" ]]; do
        steps=$((steps + 1))
        [[ $steps -gt 50 ]] && die "Upgrade chain exceeded 50 steps — possible cycle."

        # Find next version in the chain
        next=""
        if $LOCAL_MODE; then
            # Local: glob for upgrade files
            matches=()
            for f in "$REPO_ROOT"/supabase_rbac--"${current}"--*.sql; do
                [[ -f "$f" ]] && matches+=("$f")
            done
            if [[ ${#matches[@]} -eq 0 ]]; then
                die "No upgrade path from $current. Missing supabase_rbac--${current}--*.sql"
            fi
            if [[ ${#matches[@]} -gt 1 ]]; then
                die "Ambiguous upgrade path from $current. Found: ${matches[*]}"
            fi
            next=$(basename "${matches[0]}" | sed 's/supabase_rbac--[0-9][0-9.]*--\([0-9][0-9.]*\)\.sql/\1/')
        else
            # Remote: read from VERSIONS manifest
            next=$(echo "$manifest" | grep "^${current}>" | cut -d'>' -f2 | tr -d '[:space:]')
            [[ -z "$next" ]] && die "No upgrade path from $current to $VERSION. Check available versions."
        fi

        info "Loading upgrade: $current -> $next"
        get_sql "supabase_rbac--${current}--${next}.sql" \
            | sed "s/@extschema@/${SCHEMA}/g" >> "$tmpfile"
        printf '\n' >> "$tmpfile"

        current="$next"
    done

    append_version_function >> "$tmpfile"

    # Determine output destination
    if [[ -n "$OUTPUT_FILE" ]]; then
        : # explicit -o
    elif [[ -n "$OUTPUT_DIR" ]]; then
        OUTPUT_FILE="${OUTPUT_DIR}/$(date -u +%Y%m%d%H%M%S)_upgrade_rbac.sql"
    else
        # Default: stdout
        if $DRY_RUN; then
            info "[dry-run] Would output upgrade ($FROM_VERSION -> $VERSION) to stdout ($(wc -l < "$tmpfile" | tr -d ' ') lines)"
        else
            cat "$tmpfile"
        fi
        exit 0
    fi

# ═══════════════════════════════════════════════════════════════════════════════
# FRESH INSTALL MODE
# ═══════════════════════════════════════════════════════════════════════════════
else
    sql_file="supabase_rbac--${VERSION}.sql"

    if $LOCAL_MODE && [[ ! -f "$REPO_ROOT/$sql_file" ]]; then
        die "$sql_file not found. Create it before updating default_version."
    fi

    info "Loading supabase-tenant-rbac v${VERSION}..."

    {
        printf 'CREATE SCHEMA IF NOT EXISTS %s;\n\n' "$SCHEMA"
        get_sql "$sql_file" | sed "s/@extschema@/${SCHEMA}/g"
        append_version_function
    } > "$tmpfile"

    # Determine output destination
    if [[ -n "$OUTPUT_FILE" ]]; then
        : # explicit -o
    elif [[ -n "$OUTPUT_DIR" ]]; then
        OUTPUT_FILE="${OUTPUT_DIR}/$(date -u +%Y%m%d%H%M%S)_install_rbac.sql"
    elif $LOCAL_MODE; then
        OUTPUT_FILE="$REPO_ROOT/supabase/migrations/20240502214828_install_rbac.sql"
    elif [[ -d "supabase/migrations" ]]; then
        OUTPUT_FILE="supabase/migrations/$(date -u +%Y%m%d%H%M%S)_install_rbac.sql"
    else
        die "No output directory found. Use --output-dir or run 'supabase init' first."
    fi
fi

# --- Write output ---
if $DRY_RUN; then
    info "[dry-run] Would write: $OUTPUT_FILE ($(wc -l < "$tmpfile" | tr -d ' ') lines)"
    exit 0
fi

# In local mode with the fixed migration path, skip write if unchanged
if $LOCAL_MODE && [[ "$OUTPUT_FILE" = "$REPO_ROOT/supabase/migrations/20240502214828_install_rbac.sql" ]]; then
    if diff -q "$tmpfile" "$OUTPUT_FILE" > /dev/null 2>&1; then
        info "install_rbac migration is already up to date (v${VERSION})"
        exit 0
    fi
fi

cp "$tmpfile" "$OUTPUT_FILE"
info "Created $OUTPUT_FILE"

# Show next steps for remote users
if ! $LOCAL_MODE; then
    echo ""
    info "Next steps:"
    info "  1. Apply the migration:"
    info "       supabase migration up"
    info "       # or: supabase db reset"
    info "  2. Add RLS policies:"
    info "       https://github.com/point-source/supabase-tenant-rbac/blob/main/examples/policies/quickstart.sql"
fi
